name: CI

on:
  # Triggers the workflow on push or pull request events for all branches
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      buildEnv:
        description: 'Build Environment'
        required: true
        default: 'production'
      runTests:
        desctiption: 'Run unit tests?'
        required: true
        default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
      
      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      
      - name: Install dependencies
        run: npm ci
      
      # build creates a rolled up javascript deliverable file
      - name: Run build action ${{ github.event.inputs.buildEnv }}
        run: npm run build
        env:
          NODE_ENV: ${{ github.event.inputs.buildEnv }}
          BUILD_TESTS: ${{ github.event.inputs.runTests }}
      
      - name: Run unit tests
        if: github.event.inputs.runTests != 'no'
        run: npm run test

      - name: Upload minified javascript
        uses: actions/upload-artifact@v2
        with:
          name: JsBlip.js
          path: ./build/JsBlip.js
          retention-days: 1
